"""user model with relation

Revision ID: 4fce409da930
Revises: ca2303956a84
Create Date: 2021-07-06 10:43:20.397161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fce409da930'
down_revision = 'ca2303956a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=132), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=132), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('link', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'link', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_column('link', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
